Shop Facade API Specification - GET Permits and UPNs endpoints
UKHO/Shop-Facade pull request #10
Opened 2024-12-30 12:48 UTC by vijendr13545

This PR contains API specification for the Shop Facade Service. Currently only 2 API endpoint definitions are ready and should be reviewed. They are:

`GET /licences/{licenceId}/s100/permits`
`GET /licences/{licenceId}/s100/userpermits`

Other API endpoints that are tagged as "DRAFT" are not part of first phase of MVP service and they will be defined later. They should be ignored for the review.

2024-12-30 12:55 UTC, vijendr13545 commented on Shop-Facade-Open-Api-Spec.yaml
> +          description: Too Many Requests.
Would we implement any throttling for Shop Facade Service and hence is it needed?

2025-01-03 10:36 UTC, k1500666 commented on Shop-Facade-Open-Api-Spec.yaml
> +  /licences/{licenceId}/s100/userpermits:
capital P for userPermits

2025-01-03 10:56 UTC, k1500666 commented on Shop-Facade-Open-Api-Spec.yaml
> +      description: Returns a zip file containing all the S-100 permit file(s) of the requested licence.
Add tag Licensing

2025-01-03 11:00 UTC, k1500666 commented on Shop-Facade-Open-Api-Spec.yaml
> +        licenceId:
licenceId should be an integer

2025-01-03 13:02 UTC, vijendr13545 commented on Shop-Facade-Open-Api-Spec.yaml
> +        licenceId:
good spot, corrected it.

2025-01-09 12:42 UTC, martyn-fewtrell approved these changes
Looks good

2025-01-10 07:32 UTC, vijendr13545 commented on Shop-Facade-Open-Api-Spec.yaml
> +      description: Returns all S-100 User Permit Numbers (UPNs) associated with the requested licence. There can be one or more S-100 UPNs for a licence.
Added.

2025-01-10 07:32 UTC, vijendr13545 commented on Shop-Facade-Open-Api-Spec.yaml
> +      description: Returns a zip file containing all the S-100 permit file(s) of the requested licence.
Added.

2025-01-10 08:26 UTC, k1500666 approved these changes
Reviewed and looks good to me.

2025-01-23 08:08 UTC, rockydevnet requested changes

2025-01-23 08:08 UTC, rockydevnet commented on Shop-Facade-Open-Api-Spec.yaml
> +          - S122
S122 isn't in the initial S-100 offering? Either this needs to only have S101, S102, S104 & S111, or it needs to allow all potential future S100 standards.

2025-01-23 08:08 UTC, rockydevnet commented on Shop-Facade-Open-Api-Spec.yaml
> +    ApiManagementError:
lowercase a on apiManagementError to keep it consistent with the others.

```suggestion
    apiManagementError:
```

2025-01-23 08:08 UTC, rockydevnet commented on Shop-Facade-Open-Api-Spec.yaml
> +          description: Too Many Requests.
Shop Façade is internal, so won't be behind any API Management. I can't see us needing a 429.

2025-01-23 15:19 UTC, vijendr13545 commented on Shop-Facade-Open-Api-Spec.yaml
> +    ApiManagementError:
update it and its references.

2025-01-23 15:30 UTC, vijendr13545 commented on Shop-Facade-Open-Api-Spec.yaml
> +          description: Too Many Requests.
I agree. Removed all 429 response codes.

2025-01-24 11:57 UTC, vijendr13545 commented on Shop-Facade-Open-Api-Spec.yaml
> +        licenceId:
Updated.

2025-01-24 12:11 UTC, vijendr13545 commented on Shop-Facade-Open-Api-Spec.yaml
> +        application/xml:
Removed 429 response code.

2025-01-24 12:18 UTC, vijendr13545 commented on Shop-Facade-Open-Api-Spec.yaml
> +        application/xml:
It was a leftover from B2B API spec, updated it to application/json

2025-01-24 12:19 UTC, vijendr13545 commented on Shop-Facade-Open-Api-Spec.yaml
> +        application/xml:
Removed as it was an unused response.

2025-01-24 12:19 UTC, vijendr13545 commented on Shop-Facade-Open-Api-Spec.yaml
> +          - S122
removed s122.

2025-01-24 12:20 UTC, vijendr13545 commented on Shop-Facade-Open-Api-Spec.yaml
> +    TokenAuthenticationFailed:
Removed unreferenced responses.

2025-01-29 11:08 UTC, rockydevnet approved these changes
LGTM

2025-01-29 11:44 UTC, merged