195731 Continuous Integration Pipeline for Shop Facade
UKHO/Shop-Facade pull request #9
Opened 2024-12-30 04:53 UTC by amogh14893

PR contains changes for CI pipeline which includes jobs - Dependency checker, Unit Test and code coverage, Build and Publish binaries.

2025-01-02 11:03 UTC, mattwin1 reviewed
The devops changes LGTM.
There are some changes to the .sln and test code too, please can you add a brief description of these changes to the PR?

2025-01-02 12:29 UTC, jagannathsankpal approved these changes
LGTM

2025-01-02 14:11 UTC, mattwin1 approved these changes
LGTM as far as devops changes go

2025-01-02 15:26 UTC, gaurav15233 approved these changes
LGTM

2025-01-03 08:55 UTC, gaurav15233 approved these changes
LGTM

2025-01-03 12:21 UTC, DanOwenUKHO requested changes

2025-01-03 12:21 UTC, DanOwenUKHO commented on tests/UKHO.ShopFacade.API.FunctionalTests/Service/S100UpnEndpoint.cs
> +            _shoFacadeConfiguration = serviceProvider!.GetRequiredService<IOptions<ShopFacadeConfiguration>>().Value;
Can we move this dependency injection by GetRequiredService into the constructor injections, i.e. 

`public S100UpnEndpoint(IOptions<ShopFacadeConfiguration> ShopFacadeConfiguration)`

2025-01-03 12:21 UTC, DanOwenUKHO commented on src/UKHO.ShopFacade.API/Middleware/CorrelationIdMiddleware.cs
> +            var logger = httpContext.RequestServices.GetRequiredService<ILogger<CorrelationIdMiddleware>>();
Inject through constructor if possible

2025-01-03 13:05 UTC, gaurav15233 commented on src/UKHO.ShopFacade.API/Middleware/CorrelationIdMiddleware.cs
> +            var logger = httpContext.RequestServices.GetRequiredService<ILogger<CorrelationIdMiddleware>>();
Updated as suggested. Thanks

2025-01-03 13:07 UTC, gaurav15233 commented on tests/UKHO.ShopFacade.API.FunctionalTests/Service/S100UpnEndpoint.cs
> +            _shoFacadeConfiguration = serviceProvider!.GetRequiredService<IOptions<ShopFacadeConfiguration>>().Value;
As discussed this is not possible as we are creating object for this class in other class. So keeping as it is.
Thanks

2025-01-03 13:07 UTC, DanOwenUKHO approved these changes
lgtm

2025-01-03 13:16 UTC, merged